name: map_my_floor
description: "MapMyFloor indoor room navigation app using Wi-Fi fingerprinting."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^2.0.0
  wifi_scan: ^0.5.0
  permission_handler: ^13.0.2
  provider: ^6.1.2
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/final_floorplan.png
    - assets/indoor_nav/RunLevelFingerprints.csv
    - assets/indoor_nav/CheckpointGraph.json
    - assets/indoor_nav/CheckpointDefinitions.json
    - assets/indoor_nav/RoomMapping.json
